### ISSUE TITLE
Is there an open access generator from protobuf for Temporal?

### ISSUE THREAD

**Issue by FlymeDllVa** [jlegrone/tctx#6]
Hi, I saw a Temporary contract generator from protobuf on Replay. Can you tell me if this SDK is publicly available? I am very impressed with this idea that I even want to go write my own, but suddenly you will develop the SDK publicly

**Comment by jlegrone** [comment]
Thanks for the interest! I'm happy to discuss in slack. Closing this issue since it's unrelated to tctx.
